name = "bulk-file-downloader-license"
main = "worker.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "bulk-file-downloader-codes"
database_id = "4c9d874f-cbd2-4bf0-8a8f-0ecd7b5e2325"
